# Generated by Django 6.1 on 2026-09-04 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0004_pedido_cae_pedido_cae_vencimiento_pedido_cuit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit', models.CharField(blank=True, max_length=20)),
                ('razon_social', models.CharField(blank=True, max_length=200)),
                ('punto_venta', models.CharField(blank=True, max_length=20)),
                ('condicion_iva', models.CharField(blank=True, choices=[('monotributo', 'Monotributo'), ('responsable_inscripto', 'Responsable Inscripto'), ('exento', 'Exento')], max_length=60)),
                ('cert_ref', models.CharField(blank=True, max_length=200)),
                ('homologacion', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('facturar_automatico', models.BooleanField(default=False)),
                ('facturar_medios', models.JSONField(blank=True, default=list)),
                ('facturar_monto_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración fiscal',
                'verbose_name_plural': 'Configuración fiscal',
            },
        ),
        migrations.CreateModel(
            name='ComprobanteFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('ok', 'Emitido'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('cae', models.CharField(blank=True, max_length=40)),
                ('cae_vencimiento', models.DateField(blank=True, null=True)),
                ('punto_venta', models.CharField(blank=True, max_length=20)),
                ('numero_factura', models.CharField(blank=True, max_length=40)),
                ('tipo_comprobante', models.CharField(blank=True, max_length=20)),
                ('error_msg', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comprobante', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'Comprobante fiscal',
                'verbose_name_plural': 'Comprobantes fiscales',
                'ordering': ['-creado'],
            },
        ),
    ]
