# Generated by Django 6.1 on 2026-08-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0008_configuracionsitio_mensaje_cerrado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='logo_secundario',
            field=models.ImageField(blank=True, null=True, upload_to='sitio/logos/'),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='instagram',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
