# Generated by Django 6.1 on 2026-08-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0009_configuracionsitio_logo_secundario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsitio',
            name='color_acento',
            field=models.CharField(default='#8caa78', max_length=7),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='color_boton_agregar',
            field=models.CharField(default='#8caa78', max_length=7),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='color_fondo',
            field=models.CharField(default='#26382c', max_length=7),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='color_navbar',
            field=models.CharField(default='#26382c', max_length=7),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='color_superficie',
            field=models.CharField(default='#324a3a', max_length=7),
        ),
    ]
