# Generated by Django 6.1 on 2026-08-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0010_alter_configuracionsitio_color_acento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsitio',
            name='color_acento',
            field=models.CharField(default='#1a361b', max_length=7),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='color_boton_agregar',
            field=models.CharField(default='#1a361b', max_length=7),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='color_fondo',
            field=models.CharField(default='#eaf0e6', max_length=7),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='color_navbar',
            field=models.CharField(default='#f2f7ef', max_length=7),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='color_superficie',
            field=models.CharField(default='#f2f7ef', max_length=7),
        ),
    ]
