# Generated by Django 6.1 on 2026-08-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0011_alter_configuracionsitio_color_acento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='imagen_banner_mayorista',
            field=models.ImageField(blank=True, help_text="Fondo del banner 'Explorá nuestro catálogo'. Formato cuadrado (1:1) recomendado.", null=True, upload_to='sitio/banners/'),
        ),
    ]
