# Generated by Django 6.1 on 2026-08-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0012_configuracionsitio_imagen_banner_mayorista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsitio',
            name='instagram',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
