# Generated by Django 6.1 on 2026-08-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0013_alter_configuracionsitio_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='imagen_quienes_somos',
            field=models.ImageField(blank=True, help_text='Reemplaza los 2 logos de la sección de marcas. Formato vertical 9:16 recomendado.', null=True, upload_to='sitio/quienes-somos/'),
        ),
    ]
