# Generated by Django 6.1 on 2026-09-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0014_configuracionsitio_imagen_quienes_somos'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='instagram_descripcion',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='instagram_secundario',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='instagram_secundario_descripcion',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
