# Generated by Django 6.1 on 2026-09-02 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0015_configuracionsitio_instagram_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoWhatsapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('numero', models.CharField(max_length=20)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Contactos de WhatsApp',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
