# Generated by Django 6.1 on 2026-09-01 20:22

from django.db import migrations, models

MAPA = {'insumos': 'Insumos', 'servicios': 'Servicios', 'sueldos': 'Sueldos', 'otros': 'Otros'}


def normalizar_rubros(apps, schema_editor):
    """Los rubros eran un enum de slugs; ahora son texto libre (con su nombre "lindo")
    respaldado por CategoriaGasto. Pasamos los datos viejos y sembramos la lista."""
    Gasto = apps.get_model('gastos', 'Gasto')
    GastoFijo = apps.get_model('gastos', 'GastoFijo')
    CategoriaGasto = apps.get_model('gastos', 'CategoriaGasto')

    for viejo, nuevo in MAPA.items():
        Gasto.objects.filter(categoria=viejo).update(categoria=nuevo)
        GastoFijo.objects.filter(categoria=viejo).update(categoria=nuevo)

    nombres = {'Servicios', 'Sueldos', 'Otros'}
    nombres |= set(Gasto.objects.exclude(categoria='').values_list('categoria', flat=True))
    nombres |= set(GastoFijo.objects.exclude(categoria='').values_list('categoria', flat=True))
    for nombre in nombres:
        CategoriaGasto.objects.get_or_create(nombre=nombre)


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0006_insumo_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gastofijo',
            name='categoria',
            field=models.CharField(default='Otros', max_length=50),
        ),
        migrations.RunPython(normalizar_rubros, migrations.RunPython.noop),
    ]
