# Generated by Django 6.1 on 2026-09-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0007_categoriagasto_alter_gasto_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='gastofijo',
            name='categoria',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
