# Generated by Django 6.1 on 2026-08-23 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='caja',
        ),
        migrations.DeleteModel(
            name='Caja',
        ),
    ]
