# Generated by Django 6.1 on 2026-09-01 17:20

from django.db import migrations, models


def colapsar_estados_preparacion(apps, schema_editor):
    # Se elimina el flujo de preparación: cualquier pedido que no esté cancelado
    # pasa a 'pendiente' (= vigente).
    Pedido = apps.get_model('pedidos', 'Pedido')
    Pedido.objects.exclude(estado='cancelado').update(estado='pendiente')


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_remove_pedido_caja_delete_caja'),
    ]

    operations = [
        migrations.RunPython(colapsar_estados_preparacion, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Vigente'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
