# Generated by Django 6.1 on 2026-09-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cae',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cae_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cuit',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='excluir_fiscal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='facturado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_facturacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='pedido',
            name='punto_venta_factura',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_factura',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
