# Generated by Django 6.1 on 2026-09-14 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_pedido_cae_pedido_cae_vencimiento_pedido_cuit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='dni',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
