# Generated by Django 6.1 on 2026-08-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_seed_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='cantidad_minima_variedad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
