# Generated by Django 6.1 on 2026-08-24 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_seed_hierbas_y_blends'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='granel_cantidad_minima',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='categoria',
            name='granel_cantidad_minima_variedad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_granel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
