# Generated by Django 6.1 on 2026-08-31 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_borrar_granel_duplicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='venta_cantidad_fija',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CantidadFija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cantidades_fijas', to='productos.categoria')),
            ],
            options={
                'verbose_name_plural': 'Cantidades fijas',
                'ordering': ['categoria', 'cantidad'],
                'unique_together': {('categoria', 'cantidad')},
            },
        ),
    ]
