# Generated by Django 6.1 on 2026-08-31 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_corregir_yuyitos_combo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/categorias/galeria/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='productos.categoria')),
            ],
            options={
                'verbose_name_plural': 'Imágenes de categoría',
                'ordering': ['categoria', 'orden', 'creado'],
            },
        ),
    ]
