# Generated by Django 6.1 on 2026-09-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_imagencategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='alicuota_iva',
            field=models.DecimalField(decimal_places=2, default=21, max_digits=5),
        ),
    ]
