# Generated by Django 6.1 on 2026-09-01 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='insumo',
        ),
        migrations.AddField(
            model_name='compra',
            name='detalle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='compras.proveedor'),
        ),
    ]
